export async function generateOutput(apiKey, ticketType, transcript, author = '', fixedAnswers = {}, questions = []) {
  const today = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })
  const authorLine = author ? `Author: ${author}` : ''

  const context = transcript.length
    ? transcript.map(m => `${m.role === 'ai' ? 'Interviewer' : 'User'}: ${m.text}`).join('\n')
    : questions.map(q => `${q.label}: ${fixedAnswers[q.id] || 'Not provided'}`).join('\n')

  const prompt = buildOutputPrompt(ticketType, context, author, today)

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }],
    }),
  })

  if (!response.ok) {
    const err = await response.json().catch(() => ({}))
    throw new Error(err?.error?.message || `API error ${response.status}`)
  }

  const data = await response.json()
  return data.content[0].text
}

function buildOutputPrompt(type, context, author, date) {
  const authorSection = author ? `\nOwner: ${author}` : ''

  const templates = {
    epic: `You are an expert product manager. Based on the interview below, generate a comprehensive PRD/Epic document in Markdown.

Interview:
${context}

Generate a complete, professional document using this exact structure. Be specific and detailed — no vague placeholders:

---
TICKET_SUMMARY: [One clear sentence: what this epic delivers and why]
PRIORITY: [Critical / High / Medium / Low — infer from context]
---

# [Feature Name]

${authorSection}
Date: ${date}
Status: Draft

## 1. Overview
[2-3 paragraph overview of what this is, why we're building it, and the business context]

## 2. Objectives
[Bulleted list of specific, measurable objectives]

## 3. Scope

### 3.1 In Scope
[Everything explicitly included]

### 3.2 Out of Scope
[Everything explicitly excluded — be specific]

## 4. Requirements

[For each major area, create a subsection like "4.1 Feature Name" with:
- Numbered requirements list
- Be specific about behaviour, configuration, data rules, etc.]

## 5. Affected Users & Brands
[Who is affected — users, brands, offices, CRMs]

## 6. CRM / Integration Compatibility
[Any CRM or integration compatibility rules]

## 7. Dependencies & Constraints
[Technical dependencies, team dependencies, timeline constraints]

## 8. Deliverables
[Concrete list of what will be delivered]

## 9. Success Criteria
[How we'll know this is done and working]

---
*Generated by ScopeCreeper*`,

    story: `You are an expert product manager. Based on the interview below, generate a Jira User Story in Markdown.

Interview:
${context}

Generate a complete, professional user story using this exact structure:

---
TICKET_SUMMARY: As a [user role], I want [goal] so that [benefit]
PRIORITY: [Critical / High / Medium / Low — infer from context]
---

## User Story
As a **[user role]**, I want **[goal]** so that **[benefit/reason]**.

## Background / Context
[1-2 paragraphs explaining why this is needed and any relevant background]

## Acceptance Criteria
[Numbered list of specific, testable acceptance criteria using Given/When/Then or plain language]

## Edge Cases & Error States
[Bulleted list of edge cases, error scenarios, and how they should be handled]

## UI / UX Notes
[Any UI/UX requirements, design references, or behavioural specifics]

## Out of Scope
[What is explicitly NOT included in this story]

## Dependencies
[Other stories, APIs, or systems this depends on]

## Definition of Done
- [ ] [Specific checklist items]

---
*Generated by ScopeCreeper*`,

    bug: `You are an expert QA engineer and product manager. Based on the interview below, generate a detailed Jira Bug Report in Markdown.

Interview:
${context}

Generate a complete bug report using this exact structure:

---
TICKET_SUMMARY: [Bug: one-line description of what's broken]
PRIORITY: [Critical / High / Medium / Low — infer from severity and impact]
---

## Bug Summary
[1-2 sentences describing the bug clearly]

## Environment
| Field | Value |
|-------|-------|
| Browser/Device | [value] |
| Version/Build | [value] |
| Brand/Client | [value] |
| User Type | [value] |

## Steps to Reproduce
1. [Step 1]
2. [Step 2]
3. [etc.]

## Expected Behaviour
[What should happen]

## Actual Behaviour
[What actually happens]

## Frequency
[Always / Intermittent / Specific conditions]

## Business Impact
[Who is affected and what's the impact]

## Evidence
[Screenshots, logs, error messages mentioned]

## Possible Cause
[If there's enough context to suggest a root cause]

---
*Generated by ScopeCreeper*`,

    task: `You are an expert product manager. Based on the interview below, generate a detailed Jira Task in Markdown.

Interview:
${context}

Generate a complete task using this exact structure:

---
TICKET_SUMMARY: [One clear action-oriented sentence describing the task]
PRIORITY: [Critical / High / Medium / Low — infer from context]
---

## Overview
[2-3 sentences on what needs doing and why]

## Background / Context
[Relevant context, what triggered this task, how it fits into the bigger picture]

## Technical Approach
[Implementation notes, approach, or technical considerations]

## Checklist
- [ ] [Specific sub-task]
- [ ] [Specific sub-task]
[etc.]

## Dependencies
[Any blockers or dependencies on other work]

## Definition of Done
- [ ] [Specific, verifiable completion criteria]

---
*Generated by ScopeCreeper*`,

    spike: `You are an expert product manager. Based on the interview below, generate a detailed Spike/Research ticket in Markdown.

Interview:
${context}

---
TICKET_SUMMARY: [Spike: one sentence describing what's being investigated]
PRIORITY: [Critical / High / Medium / Low]
---

## Research Question
[The core question(s) this spike must answer]

## Background
[Why this research is needed and what's driving it]

## Timebox
[Maximum time to spend: X days / X points]

## In Scope
[What will be investigated]

## Out of Scope
[What won't be investigated in this spike]

## Expected Outputs
[What will be produced: document, recommendation, prototype, ADR, etc.]

## Success Criteria
[How we'll know the spike answered the question]

## References
[Related tickets, docs, or prior work]

---
*Generated by ScopeCreeper*`,

    template: `You are an expert product manager. Based on the interview below, generate a Jira Template Change ticket in Markdown.

Interview:
${context}

---
TICKET_SUMMARY: [Template Change: one sentence describing the change]
PRIORITY: [Critical / High / Medium / Low]
---

## Overview
[What template is changing and why]

## Current State
[What it currently looks like / does]

## Desired Change
[Exactly what needs to change — be specific]

## Affected Brands / Variants
[Which brands, offices, or template variants are impacted]

## OBP / Configuration
[Any OBP toggles, settings, or configuration involved]

## Behaviour Rules
[Specific conditional logic or display rules]

## Design Reference
[Any designs, Canva links, or visual examples mentioned]

## Risk / Impact
[Any risk to other parts of the system or other brands]

## Definition of Done
- [ ] [Specific completion criteria]

---
*Generated by ScopeCreeper*`,
  }

  return templates[type] || templates.task
}
